# Generated by Django 4.2.28 on 2026-02-10 02:11

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='Requis. 150 caractères ou moins. Lettres, chiffres et @/./+/-/_ uniquement.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('email', models.EmailField(help_text='Requis. Une adresse email valide.', max_length=254, unique=True)),
                ('email_recuperation', models.EmailField(blank=True, help_text='Adresse email de récupération optionnelle.', max_length=254, null=True, verbose_name='Email de récupération')),
                ('phone_number', models.CharField(blank=True, help_text='Numéro de téléphone avec indicatif pays optionnel.', max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('address', models.TextField(blank=True, help_text='Adresse physique.', null=True, verbose_name='Adresse')),
                ('country', models.CharField(blank=True, help_text='Pays de résidence.', max_length=100, null=True, verbose_name='Pays')),
                ('avatar', models.ImageField(blank=True, help_text='Photo de profil.', null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, help_text='Courte biographie.', null=True, verbose_name='Biographie')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderateur'), ('user', 'Utilisateur')], default='user', help_text="Rôle utilisateur pour le contrôle d'accès.", max_length=20, verbose_name='Rôle')),
                ('is_email_verified', models.BooleanField(default=False, help_text="Indique si l'utilisateur a vérifié son email.", verbose_name='Email vérifié')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si ce compte doit être considéré comme actif.', verbose_name='Actif')),
                ('is_blocked', models.BooleanField(default=False, help_text='Indique si ce compte est bloqué.', verbose_name='Bloqué')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
